update ci

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -114,6 +114,25 @@ TestDecomposition:
     paths:
       - mnist-modular/Streamtest/output/*
 
+TestTransfer:
+  stage: test
+  image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/mxnet/190:v0.0.2
+  when: always
+  script:
+    - export TZ=Europe/Berlin
+    - apt update && DEBIAN_FRONTEND=noninteractive apt install -y tzdata libomp-dev libopencv-dev python3-opencv
+    - ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime
+    - dpkg-reconfigure --frontend noninteractive tzdata
+    - python3 -m pip install -U pip scikit-image opencv-python
+    - ln -fs /usr/bin/python3 /usr/bin/python
+    - cd transfer
+    - RES=$(./runTransfer.sh 2>&1)
+    - STATUS=$?
+    - |
+      if [[ $STATUS -ne 0 ]]; then
+        echo "Error during transfer learning: $RES"
+        exit $STATUS
+      fi
 
 TestMnistWithAdaNet:
   stage: test
