Added cancel in progress

diff --git a/.github/workflows/3d-gan.yml b/.github/workflows/3d-gan.yml
--- a/.github/workflows/3d-gan.yml
+++ b/.github/workflows/3d-gan.yml
@@ -6,10 +6,13 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 59285
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
-  cibuild : ${{ secrets.SE_NEXUS_PASSWORD }}
+  CI_PROJECT_ID: 59285
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   FileChanges:
     runs-on: ubuntu-latest
@@ -40,29 +43,29 @@ jobs:
           echo "Final file status only check: $only"
           echo "run=$only" >> $GITHUB_OUTPUT
   docker_phase:
-    needs: [buildDockerMxNet180]
+    needs: [ buildDockerMxNet180 ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage docker"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage docker"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage docker"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage docker"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
   jar_phase:
-    needs: [docker_phase, TestWithJar]
+    needs: [ docker_phase, TestWithJar ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage jar"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage jar"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage jar"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage jar"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   buildDockerMxNet180:
     needs: FileChanges
@@ -78,12 +81,12 @@ jobs:
         shell: bash
         continue-on-error: true
         run: |
-            cd applications/gans/3d-gan
-            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
-            cd Gluon/.test/docker
-            LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
-            docker build -t ghcr.io/$LOWERCASE_OWNER/mxnet180 .
-            docker push ghcr.io/$LOWERCASE_OWNER/mxnet180
+          cd applications/gans/3d-gan
+          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
+          cd Gluon/.test/docker
+          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
+          docker build -t ghcr.io/$LOWERCASE_OWNER/mxnet180 .
+          docker push ghcr.io/$LOWERCASE_OWNER/mxnet180
 
   Train3D-GAN:
     needs: jar_phase
diff --git a/.github/workflows/EMADL2CPP.yml b/.github/workflows/EMADL2CPP.yml
--- a/.github/workflows/EMADL2CPP.yml
+++ b/.github/workflows/EMADL2CPP.yml
@@ -6,10 +6,13 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 17712
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
-  cibuild : ${{ secrets.SE_NEXUS_PASSWORD }}
+  CI_PROJECT_ID: 17712
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   FileChanges:
     runs-on: ubuntu-latest
@@ -151,41 +154,41 @@ jobs:
           echo "Final file status only check: $only"
           echo "run=$only" >> $GITHUB_OUTPUT
   docker_phase:
-    needs: [buildDockerTensorflowONNX, buildDockerPyTorch, buildDockerMXNet170DGL, buildDockerMXNet170, buildDockerDGLQD, buildDockerMXNet150, buildDockerMXNet170onnx]
+    needs: [ buildDockerTensorflowONNX, buildDockerPyTorch, buildDockerMXNet170DGL, buildDockerMXNet170, buildDockerDGLQD, buildDockerMXNet150, buildDockerMXNet170onnx ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage docker"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage docker"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage docker"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage docker"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
   linux_phase:
-    needs: [docker_phase, artifact-extraction, integrationMXNetJobLinux, integrationGluonJobLinux, integrationCaffe2JobLinux, integrationPythonWrapperTest, integrationTensorflowJobLinux, modularityTest, integrationPyTorchJobLinux, UnitTestJobLinux]
+    needs: [ docker_phase, artifact-extraction, integrationMXNetJobLinux, integrationGluonJobLinux, integrationCaffe2JobLinux, integrationPythonWrapperTest, integrationTensorflowJobLinux, modularityTest, integrationPyTorchJobLinux, UnitTestJobLinux ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage linux"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage linux"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage linux"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage linux"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
   deploy_phase:
-    needs: [linux_phase, git_masterJobLinux]
+    needs: [ linux_phase, git_masterJobLinux ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage deploy"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage deploy"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage deploy"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage deploy"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   git_masterJobLinux:
     needs: linux_phase
@@ -370,7 +373,7 @@ jobs:
             generators/EMADL2CPP/target
 
   modularityTest:
-    needs: [docker_phase, FileChanges]
+    needs: [ docker_phase, FileChanges ]
     if: ${{ !cancelled() && needs.docker_phase.result == 'success' && needs.FileChanges.outputs.runmodularityTest == 'true' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
@@ -443,8 +446,8 @@ jobs:
       - name: Script
         shell: bash
         run: |
-            cd generators/EMADL2CPP
-            cd src/test/resources/docker/mxnet150
+          cd generators/EMADL2CPP
+          cd src/test/resources/docker/mxnet150
 
   buildDockerMXNet170:
     needs: FileChanges
@@ -459,8 +462,8 @@ jobs:
       - name: Script
         shell: bash
         run: |
-            cd generators/EMADL2CPP
-            cd src/test/resources/docker/mxnet170
+          cd generators/EMADL2CPP
+          cd src/test/resources/docker/mxnet170
 
   buildDockerMXNet170onnx:
     needs: FileChanges
@@ -475,8 +478,8 @@ jobs:
       - name: Script
         shell: bash
         run: |
-            cd generators/EMADL2CPP
-            cd src/test/resources/docker/mxnet170
+          cd generators/EMADL2CPP
+          cd src/test/resources/docker/mxnet170
 
   buildDockerTensorflowONNX:
     needs: FileChanges
@@ -492,12 +495,12 @@ jobs:
         shell: bash
         continue-on-error: true
         run: |
-            cd generators/EMADL2CPP
-            cd src/test/resources/docker/tensorflow
-            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
-            LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
-            docker build -t ghcr.io/$LOWERCASE_OWNER/emadl2cpp/dockerimages/tensorflow-onnx:latest -f Dockerfile-onnx .
-            docker push ghcr.io/$LOWERCASE_OWNER/emadl2cpp/dockerimages/tensorflow-onnx:latest
+          cd generators/EMADL2CPP
+          cd src/test/resources/docker/tensorflow
+          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
+          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
+          docker build -t ghcr.io/$LOWERCASE_OWNER/emadl2cpp/dockerimages/tensorflow-onnx:latest -f Dockerfile-onnx .
+          docker push ghcr.io/$LOWERCASE_OWNER/emadl2cpp/dockerimages/tensorflow-onnx:latest
 
   buildDockerMXNet170DGL:
     needs: FileChanges
@@ -512,12 +515,12 @@ jobs:
       - name: Script
         shell: bash
         run: |
-            cd generators/EMADL2CPP
-            cd src/test/resources/docker/mxnet170
-            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
-            LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
-            docker build -t ghcr.io/$LOWERCASE_OWNER/emadl2cpp/dockerimages/mxnet170-dgl:v0.0.1 -f Dockerfile-dgl .
-            docker push ghcr.io/$LOWERCASE_OWNER/emadl2cpp/dockerimages/mxnet170-dgl:v0.0.1
+          cd generators/EMADL2CPP
+          cd src/test/resources/docker/mxnet170
+          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
+          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
+          docker build -t ghcr.io/$LOWERCASE_OWNER/emadl2cpp/dockerimages/mxnet170-dgl:v0.0.1 -f Dockerfile-dgl .
+          docker push ghcr.io/$LOWERCASE_OWNER/emadl2cpp/dockerimages/mxnet170-dgl:v0.0.1
 
   buildDockerDGLQD:
     needs: FileChanges
@@ -533,12 +536,12 @@ jobs:
         shell: bash
         continue-on-error: true
         run: |
-            cd generators/EMADL2CPP
-            cd src/test/resources/docker/dglqd
-            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
-            LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
-            docker build -t ghcr.io/$LOWERCASE_OWNER/emadl2cpp/dockerimages/dgl-qd:latest -f Dockerfile .
-            docker push ghcr.io/$LOWERCASE_OWNER/emadl2cpp/dockerimages/dgl-qd:latest
+          cd generators/EMADL2CPP
+          cd src/test/resources/docker/dglqd
+          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
+          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
+          docker build -t ghcr.io/$LOWERCASE_OWNER/emadl2cpp/dockerimages/dgl-qd:latest -f Dockerfile .
+          docker push ghcr.io/$LOWERCASE_OWNER/emadl2cpp/dockerimages/dgl-qd:latest
 
   buildDockerPyTorch:
     needs: FileChanges
@@ -553,12 +556,12 @@ jobs:
       - name: Script
         shell: bash
         run: |
-            cd generators/EMADL2CPP
-            cd src/test/resources/docker/pytorch
-            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
-            LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
-            docker build -t ghcr.io/$LOWERCASE_OWNER/emadl2cpp/dockerimages/pytorch:latest -f Dockerfile .
-            docker push ghcr.io/$LOWERCASE_OWNER/emadl2cpp/dockerimages/pytorch:latest
+          cd generators/EMADL2CPP
+          cd src/test/resources/docker/pytorch
+          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
+          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
+          docker build -t ghcr.io/$LOWERCASE_OWNER/emadl2cpp/dockerimages/pytorch:latest -f Dockerfile .
+          docker push ghcr.io/$LOWERCASE_OWNER/emadl2cpp/dockerimages/pytorch:latest
 
   artifact-extraction:
     needs: docker_phase
@@ -579,11 +582,11 @@ jobs:
       - name: Script
         shell: bash
         run: |
-            cd generators/EMADL2CPP
-            apt-get update -qq && apt-get install -y -qq openjdk-11-jre-headless python3 python3-pip git
-            cd extractor
-            pip3 install -r requirements.txt
-            python3 extract.py ${{ secrets.GITLABTOKEN }}
+          cd generators/EMADL2CPP
+          apt-get update -qq && apt-get install -y -qq openjdk-11-jre-headless python3 python3-pip git
+          cd extractor
+          pip3 install -r requirements.txt
+          python3 extract.py ${{ secrets.GITLABTOKEN }}
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
         if: success()
diff --git a/.github/workflows/MNISTCalculator.yml b/.github/workflows/MNISTCalculator.yml
--- a/.github/workflows/MNISTCalculator.yml
+++ b/.github/workflows/MNISTCalculator.yml
@@ -6,47 +6,50 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 25225
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
-  cibuild : ${{ secrets.SE_NEXUS_PASSWORD }}
+  CI_PROJECT_ID: 25225
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   prebuild_phase:
-    needs: [DeployMnistCalcArtifact]
+    needs: [ DeployMnistCalcArtifact ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage prebuild"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage prebuild"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage prebuild"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage prebuild"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
   test_phase:
-    needs: [prebuild_phase, TestGluonONNX, TrainHexadecimal_MnistCalculatorTL, TrainOperator_MnistCalculator, TestTENSORFLOW, TestEMADLMavenPlugin, TestMNISTwithCustomLayer, TrainHexadecimal_MnistCalculator, TestMavenStreamtestPlugin, TestMnistWithAdaNet, TrainOperator_MnistCalculatorTL, DeployDecompositionResNetArtifact, TrainTensorflowONNX]
+    needs: [ prebuild_phase, TestGluonONNX, TrainHexadecimal_MnistCalculatorTL, TrainOperator_MnistCalculator, TestTENSORFLOW, TestEMADLMavenPlugin, TestMNISTwithCustomLayer, TrainHexadecimal_MnistCalculator, TestMavenStreamtestPlugin, TestMnistWithAdaNet, TrainOperator_MnistCalculatorTL, DeployDecompositionResNetArtifact, TrainTensorflowONNX ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage test"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage test"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage test"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage test"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
   testmodular_phase:
-    needs: [test_phase, TestTransfer, TestDecomposition, TestDecompositionResNet, TestModularModels]
+    needs: [ test_phase, TestTransfer, TestDecomposition, TestDecompositionResNet, TestModularModels ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage testmodular"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage testmodular"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage testmodular"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage testmodular"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   TestTENSORFLOW:
     needs: prebuild_phase
@@ -224,7 +227,7 @@ jobs:
             applications/MNISTCalculator/mnist-modular/Streamtest/output/*
 
   TestDecompositionResNet:
-    needs: [TestEMADLMavenPlugin, test_phase]
+    needs: [ TestEMADLMavenPlugin, test_phase ]
     if: ${{ !cancelled() && needs.test_phase.result == 'success' && needs.TestEMADLMavenPlugin.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
@@ -390,7 +393,7 @@ jobs:
             applications/MNISTCalculator/onnx/tensorflow-pretrained/model/
 
   TestGluonONNX:
-    needs: [TrainTensorflowONNX, prebuild_phase]
+    needs: [ TrainTensorflowONNX, prebuild_phase ]
     if: ${{ !cancelled() && needs.prebuild_phase.result == 'success'      && github.ref_name != 'modular_testing' && needs.TrainTensorflowONNX.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
@@ -457,7 +460,7 @@ jobs:
         run: docker exec build-container bash -c "$SCRIPT"
 
   DeployDecompositionResNetArtifact:
-    needs: [TestEMADLMavenPlugin, prebuild_phase]
+    needs: [ TestEMADLMavenPlugin, prebuild_phase ]
     if: ${{ !cancelled() && needs.prebuild_phase.result == 'success' && needs.TestEMADLMavenPlugin.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
diff --git a/.github/workflows/reporting.yml b/.github/workflows/reporting.yml
--- a/.github/workflows/reporting.yml
+++ b/.github/workflows/reporting.yml
@@ -6,23 +6,26 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 17676
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
-  cibuild : ${{ secrets.SE_NEXUS_PASSWORD }}
+  CI_PROJECT_ID: 17676
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   linux_phase:
-    needs: [masterJobLinux]
+    needs: [ masterJobLinux ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage linux"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage linux"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage linux"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage linux"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   masterJobLinux:
     if: ${{ !cancelled() && github.ref_name == 'master' }}
diff --git a/.github/workflows/torcsdprl.yml b/.github/workflows/torcsdprl.yml
--- a/.github/workflows/torcsdprl.yml
+++ b/.github/workflows/torcsdprl.yml
@@ -6,9 +6,12 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 62182
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
+  CI_PROJECT_ID: 62182
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   FileChanges:
     runs-on: ubuntu-latest
@@ -39,17 +42,17 @@ jobs:
           echo "Final file status only check: $only"
           echo "run=$only" >> $GITHUB_OUTPUT
   docker_phase:
-    needs: [buildDocker]
+    needs: [ buildDocker ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage docker"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage docker"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage docker"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage docker"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   buildDocker:
     needs: FileChanges
@@ -65,12 +68,12 @@ jobs:
         shell: bash
         continue-on-error: true
         run: |
-            cd applications/torcsdprl
-            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
-            cd Docker
-            LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
-            docker build -t ghcr.io/$LOWERCASE_OWNER/dockerimages/mxnet17 .
-            docker push ghcr.io/$LOWERCASE_OWNER/dockerimages/mxnet17
+          cd applications/torcsdprl
+          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
+          cd Docker
+          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
+          docker build -t ghcr.io/$LOWERCASE_OWNER/dockerimages/mxnet17 .
+          docker push ghcr.io/$LOWERCASE_OWNER/dockerimages/mxnet17
 
   TestBuild:
     needs: docker_phase
