Added cancel in progress

diff --git a/.github/workflows/ConfLang.yml b/.github/workflows/ConfLang.yml
--- a/.github/workflows/ConfLang.yml
+++ b/.github/workflows/ConfLang.yml
@@ -6,37 +6,40 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 55457
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
-  cibuild : ${{ secrets.SE_NEXUS_PASSWORD }}
-  MAVEN_OPTS : -Xmx4096m -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
-  MAVEN_CLI_OPTS : --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true
+  CI_PROJECT_ID: 55457
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
+  MAVEN_OPTS: -Xmx4096m -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
+  MAVEN_CLI_OPTS: --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true
+concurrency:
+  group: branch-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   build_phase:
-    needs: [build]
+    needs: [ build ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage build"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage build"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage build"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage build"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
   report_phase:
-    needs: [build_phase, ]
+    needs: [ build_phase, ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage report"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage report"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage report"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage report"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   build:
     runs-on: ubuntu-latest
@@ -60,7 +63,7 @@ jobs:
       - name: Reporting
         uses: dorny/test-reporter@v2
         continue-on-error: true
-        if : ${{ always() }}
+        if: ${{ always() }}
         with:
           name: build
           path: |
diff --git a/.github/workflows/EMAM2Middleware.yml b/.github/workflows/EMAM2Middleware.yml
--- a/.github/workflows/EMAM2Middleware.yml
+++ b/.github/workflows/EMAM2Middleware.yml
@@ -6,35 +6,38 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 17660
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
-  cibuild : ${{ secrets.SE_NEXUS_PASSWORD }}
+  CI_PROJECT_ID: 17660
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
+concurrency:
+  group: branch-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   linuxCompile_phase:
-    needs: [CompileJobLinux]
+    needs: [ CompileJobLinux ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage linuxCompile"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage linuxCompile"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage linuxCompile"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage linuxCompile"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
   integration_phase:
-    needs: [linuxCompile_phase, SomeIPIntegrationJob, Ros2IntegrationJob, RosIntegrationJob, MqttIntegrationJob]
+    needs: [ linuxCompile_phase, SomeIPIntegrationJob, Ros2IntegrationJob, RosIntegrationJob, MqttIntegrationJob ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage integration"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage integration"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage integration"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage integration"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   CompileJobLinux:
     runs-on: ubuntu-latest
@@ -65,7 +68,7 @@ jobs:
             generators/EMAM2Middleware/target/
 
   DeployJobLinux:
-    needs: [CompileJobLinux, integration_phase]
+    needs: [ CompileJobLinux, integration_phase ]
     if: ${{ !cancelled() && needs.integration_phase.result == 'success' &&  github.ref_name == 'master' && needs.CompileJobLinux.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
@@ -93,7 +96,7 @@ jobs:
         run: docker exec build-container bash -c "$SCRIPT"
 
   MqttIntegrationJob:
-    needs: [CompileJobLinux, linuxCompile_phase]
+    needs: [ CompileJobLinux, linuxCompile_phase ]
     if: ${{ !cancelled() && needs.linuxCompile_phase.result == 'success' && needs.CompileJobLinux.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
@@ -123,7 +126,7 @@ jobs:
         run: docker exec build-container bash -c "$SCRIPT"
 
   RosIntegrationJob:
-    needs: [CompileJobLinux, linuxCompile_phase]
+    needs: [ CompileJobLinux, linuxCompile_phase ]
     if: ${{ !cancelled() && needs.linuxCompile_phase.result == 'success' && needs.CompileJobLinux.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
@@ -152,7 +155,7 @@ jobs:
         run: docker exec build-container bash -c "$SCRIPT"
 
   SomeIPIntegrationJob:
-    needs: [CompileJobLinux, linuxCompile_phase]
+    needs: [ CompileJobLinux, linuxCompile_phase ]
     if: ${{ !cancelled() && needs.linuxCompile_phase.result == 'success' && needs.CompileJobLinux.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
@@ -182,7 +185,7 @@ jobs:
         run: docker exec build-container bash -c "$SCRIPT"
 
   Ros2IntegrationJob:
-    needs: [CompileJobLinux, linuxCompile_phase]
+    needs: [ CompileJobLinux, linuxCompile_phase ]
     if: ${{ !cancelled() && needs.linuxCompile_phase.result == 'success' && needs.CompileJobLinux.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
diff --git a/.github/workflows/EMAM2SomeIP.yml b/.github/workflows/EMAM2SomeIP.yml
--- a/.github/workflows/EMAM2SomeIP.yml
+++ b/.github/workflows/EMAM2SomeIP.yml
@@ -6,35 +6,38 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 29949
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
-  cibuild : ${{ secrets.SE_NEXUS_PASSWORD }}
+  CI_PROJECT_ID: 29949
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
+concurrency:
+  group: branch-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   project_phase:
-    needs: [BranchJobProject]
+    needs: [ BranchJobProject ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage project"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage project"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage project"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage project"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
   adapter_phase:
-    needs: [project_phase, BranchJobAdapter]
+    needs: [ project_phase, BranchJobAdapter ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage adapter"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage adapter"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage adapter"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage adapter"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   BranchJobDeploy:
     needs: adapter_phase
diff --git a/.github/workflows/EmbeddedMontiArcStudio3.yml b/.github/workflows/EmbeddedMontiArcStudio3.yml
--- a/.github/workflows/EmbeddedMontiArcStudio3.yml
+++ b/.github/workflows/EmbeddedMontiArcStudio3.yml
@@ -6,24 +6,27 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 39210
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
-  MAVEN_OPTS : -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
-  NODE_OPTIONS : --max-old-space-size=4096
+  CI_PROJECT_ID: 39210
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
+  NODE_OPTIONS: --max-old-space-size=4096
+concurrency:
+  group: branch-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   install_phase:
-    needs: [install]
+    needs: [ install ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage install"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage install"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage install"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage install"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   install:
     if: ${{ github.ref_name != 'master' }}
diff --git a/.github/workflows/GDL.yml b/.github/workflows/GDL.yml
--- a/.github/workflows/GDL.yml
+++ b/.github/workflows/GDL.yml
@@ -6,22 +6,25 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 60571
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
+  CI_PROJECT_ID: 60571
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+concurrency:
+  group: branch-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   build_phase:
-    needs: [build]
+    needs: [ build ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage build"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage build"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage build"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage build"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   build:
     runs-on: ubuntu-latest
diff --git a/.github/workflows/Tagging-Examples.yml b/.github/workflows/Tagging-Examples.yml
--- a/.github/workflows/Tagging-Examples.yml
+++ b/.github/workflows/Tagging-Examples.yml
@@ -6,35 +6,38 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 17646
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
-  cibuild : ${{ secrets.SE_NEXUS_PASSWORD }}
+  CI_PROJECT_ID: 17646
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
+concurrency:
+  group: branch-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   EMA_phase:
-    needs: [TaggingEMA]
+    needs: [ TaggingEMA ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage EMA"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage EMA"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage EMA"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage EMA"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
   CD4A_phase:
-    needs: [EMA_phase, TaggingCD4A]
+    needs: [ EMA_phase, TaggingCD4A ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage CD4A"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage CD4A"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage CD4A"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage CD4A"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   TaggingEMA:
     runs-on: ubuntu-latest
diff --git a/.github/workflows/hardware_emulator.yml b/.github/workflows/hardware_emulator.yml
--- a/.github/workflows/hardware_emulator.yml
+++ b/.github/workflows/hardware_emulator.yml
@@ -6,36 +6,39 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 23385
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
-  cibuild : ${{ secrets.SE_NEXUS_PASSWORD }}
-  GIT_SUBMODULE_STRATEGY : recursive
+  CI_PROJECT_ID: 23385
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
+  GIT_SUBMODULE_STRATEGY: recursive
+concurrency:
+  group: branch-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   build_phase:
-    needs: [build_hardware_emulator]
+    needs: [ build_hardware_emulator ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage build"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage build"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage build"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage build"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
   test_phase:
-    needs: [build_phase, ]
+    needs: [ build_phase, ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage test"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage test"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage test"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage test"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   build_hardware_emulator:
     runs-on: ubuntu-latest
@@ -48,9 +51,9 @@ jobs:
       - name: Script
         shell: bash
         run: |
-            cd simulators/hardware_emulator
-            chmod +x ./scripts/unix/build_emulator.sh
-            ./scripts/unix/build_emulator.sh
+          cd simulators/hardware_emulator
+          chmod +x ./scripts/unix/build_emulator.sh
+          ./scripts/unix/build_emulator.sh
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
         if: success()
@@ -61,7 +64,7 @@ jobs:
             simulators/hardware_emulator/src/main/resources/linux/hardware_emulator_lib.so
 
   linux_maven_master:
-    needs: [build_hardware_emulator, test_phase]
+    needs: [ build_hardware_emulator, test_phase ]
     if: ${{ !cancelled() && needs.test_phase.result == 'success' &&  github.ref_name == 'master' && needs.build_hardware_emulator.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
@@ -91,7 +94,7 @@ jobs:
         run: docker exec build-container bash -c "$SCRIPT"
 
   linux_maven_branch:
-    needs: [build_hardware_emulator, test_phase]
+    needs: [ build_hardware_emulator, test_phase ]
     if: ${{ !cancelled() && needs.test_phase.result == 'success'      && github.ref_name != 'master' && needs.build_hardware_emulator.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
diff --git a/.github/workflows/simulation.yml b/.github/workflows/simulation.yml
--- a/.github/workflows/simulation.yml
+++ b/.github/workflows/simulation.yml
@@ -6,35 +6,38 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 17704
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
-  cibuild : ${{ secrets.SE_NEXUS_PASSWORD }}
+  CI_PROJECT_ID: 17704
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
+concurrency:
+  group: branch-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   windows_phase:
-    needs: []
+    needs: [ ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage windows"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage windows"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage windows"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage windows"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
   linux_phase:
-    needs: [windows_phase, BranchJobLinux, MasterJobLinux]
+    needs: [ windows_phase, BranchJobLinux, MasterJobLinux ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage linux"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage linux"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage linux"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage linux"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   MasterJobLinux:
     needs: windows_phase
