Added cancel in progress

diff --git a/.github/workflows/CooperativeIntersection.yml b/.github/workflows/CooperativeIntersection.yml
--- a/.github/workflows/CooperativeIntersection.yml
+++ b/.github/workflows/CooperativeIntersection.yml
@@ -6,22 +6,25 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 26302
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
+  CI_PROJECT_ID: 26302
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   generate_phase:
-    needs: [gen]
+    needs: [ gen ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage generate"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage generate"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage generate"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage generate"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   gen:
     runs-on: ubuntu-latest
@@ -53,7 +56,7 @@ jobs:
             applications/CooperativeIntersection/target/
 
   comp:
-    needs: [gen, generate_phase]
+    needs: [ gen, generate_phase ]
     if: ${{ !cancelled() && needs.generate_phase.result == 'success' && needs.gen.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
diff --git a/.github/workflows/GDLTools.yml b/.github/workflows/GDLTools.yml
--- a/.github/workflows/GDLTools.yml
+++ b/.github/workflows/GDLTools.yml
@@ -6,23 +6,26 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 69053
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
-  cibuild : ${{ secrets.SE_NEXUS_PASSWORD }}
+  CI_PROJECT_ID: 69053
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   linuxCompile_phase:
-    needs: [CompileJobLinux]
+    needs: [ CompileJobLinux ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage linuxCompile"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage linuxCompile"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage linuxCompile"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage linuxCompile"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   CompileJobLinux:
     runs-on: ubuntu-latest
@@ -53,7 +56,7 @@ jobs:
             utilities/GDLTools/target/
 
   DeployJobLinux:
-    needs: [CompileJobLinux, linuxCompile_phase]
+    needs: [ CompileJobLinux, linuxCompile_phase ]
     if: ${{ !cancelled() && needs.linuxCompile_phase.result == 'success' && needs.CompileJobLinux.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
diff --git a/.github/workflows/Struct.yml b/.github/workflows/Struct.yml
--- a/.github/workflows/Struct.yml
+++ b/.github/workflows/Struct.yml
@@ -6,10 +6,13 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 17656
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
-  cibuild : ${{ secrets.SE_NEXUS_PASSWORD }}
+  CI_PROJECT_ID: 17656
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   FileChanges:
     runs-on: ubuntu-latest
@@ -46,20 +49,20 @@ jobs:
           echo "Final file status except check: $exc"
           echo "run=$exc" >> $GITHUB_OUTPUT
   windows_phase:
-    needs: []
+    needs: [ ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage windows"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage windows"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage windows"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage windows"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   masterJobLinux:
-    needs: [windows_phase, FileChanges]
+    needs: [ windows_phase, FileChanges ]
     if: ${{ !cancelled() && needs.windows_phase.result == 'success' &&  github.ref_name == 'master' && needs.FileChanges.outputs.runmasterJobLinux == 'true' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
diff --git a/.github/workflows/TicTacToeAgent.yml b/.github/workflows/TicTacToeAgent.yml
--- a/.github/workflows/TicTacToeAgent.yml
+++ b/.github/workflows/TicTacToeAgent.yml
@@ -6,35 +6,38 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 69051
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
-  cibuild : ${{ secrets.SE_NEXUS_PASSWORD }}
+  CI_PROJECT_ID: 69051
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   linuxBuildJava17_phase:
-    needs: [TestBuildJava17]
+    needs: [ TestBuildJava17 ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage linuxBuildJava17"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage linuxBuildJava17"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage linuxBuildJava17"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage linuxBuildJava17"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
   linuxBuildJava1_8_phase:
-    needs: [linuxBuildJava17_phase, TestBuildJava1_8]
+    needs: [ linuxBuildJava17_phase, TestBuildJava1_8 ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage linuxBuildJava1_8"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage linuxBuildJava1_8"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage linuxBuildJava1_8"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage linuxBuildJava1_8"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   TestBuildJava17:
     runs-on: ubuntu-latest
@@ -53,17 +56,17 @@ jobs:
       - name: Script
         shell: bash
         run: |
-            cd applications/reinforcement_learning/TicTacToeAgent
-            apt-get update
-            apt-get install software-properties-common -y
-            apt-get install -y gnupg2
-            echo "deb http://ppa.launchpad.net/swi-prolog/stable/ubuntu $(cat /etc/os-release | grep -oP -m 1 "VERSION_CODENAME=\K\w+") main" | tee -a /etc/apt/sources.list
-            echo "deb-src http://ppa.launchpad.net/swi-prolog/stable/ubuntu $(cat /etc/os-release | grep -oP -m 1 "VERSION_CODENAME=\K\w+") main" | tee -a /etc/apt/sources.list
-            apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EF8406856DBFCA18
-            apt-add-repository ppa:swi-prolog/stable -y 2>/dev/null
-            apt-get install -y swi-prolog
-            cd tictactoe-environment
-            mvn clean package -s settings.xml
+          cd applications/reinforcement_learning/TicTacToeAgent
+          apt-get update
+          apt-get install software-properties-common -y
+          apt-get install -y gnupg2
+          echo "deb http://ppa.launchpad.net/swi-prolog/stable/ubuntu $(cat /etc/os-release | grep -oP -m 1 "VERSION_CODENAME=\K\w+") main" | tee -a /etc/apt/sources.list
+          echo "deb-src http://ppa.launchpad.net/swi-prolog/stable/ubuntu $(cat /etc/os-release | grep -oP -m 1 "VERSION_CODENAME=\K\w+") main" | tee -a /etc/apt/sources.list
+          apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EF8406856DBFCA18
+          apt-add-repository ppa:swi-prolog/stable -y 2>/dev/null
+          apt-get install -y swi-prolog
+          cd tictactoe-environment
+          mvn clean package -s settings.xml
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
         if: success()
@@ -74,7 +77,7 @@ jobs:
             applications/reinforcement_learning/TicTacToeAgent/tictactoe-environment/target/
 
   TestBuildJava1_8:
-    needs: [TestBuildJava17, linuxBuildJava17_phase]
+    needs: [ TestBuildJava17, linuxBuildJava17_phase ]
     if: ${{ !cancelled() && needs.linuxBuildJava17_phase.result == 'success' && needs.TestBuildJava17.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
@@ -120,7 +123,7 @@ jobs:
             applications/reinforcement_learning/TicTacToeAgent/tictactoe-agent/generator-target/
 
   TestTrain:
-    needs: [TestBuildJava17 , TestBuildJava1_8, linuxBuildJava1_8_phase]
+    needs: [ TestBuildJava17 , TestBuildJava1_8, linuxBuildJava1_8_phase ]
     if: ${{ !cancelled() && needs.linuxBuildJava1_8_phase.result == 'success' && needs.TestBuildJava17.result == 'success' && needs.TestBuildJava1_8.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
diff --git a/.github/workflows/crfrnn.yml b/.github/workflows/crfrnn.yml
--- a/.github/workflows/crfrnn.yml
+++ b/.github/workflows/crfrnn.yml
@@ -6,9 +6,12 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 37607
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
+  CI_PROJECT_ID: 37607
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   FileChanges:
     runs-on: ubuntu-latest
@@ -45,29 +48,29 @@ jobs:
           echo "Final file status except check: $exc"
           echo "run=$exc" >> $GITHUB_OUTPUT
   mnistsmallseg_phase:
-    needs: [TestMNIST]
+    needs: [ TestMNIST ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage mnistsmallseg"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage mnistsmallseg"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage mnistsmallseg"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage mnistsmallseg"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
   unet_phase:
-    needs: [mnistsmallseg_phase, ]
+    needs: [ mnistsmallseg_phase, ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage unet"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage unet"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage unet"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage unet"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   TestMNIST:
     needs: FileChanges
diff --git a/.github/workflows/emadl-maven-plugin.yml b/.github/workflows/emadl-maven-plugin.yml
--- a/.github/workflows/emadl-maven-plugin.yml
+++ b/.github/workflows/emadl-maven-plugin.yml
@@ -6,10 +6,13 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 49355
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
-  cibuild : ${{ secrets.SE_NEXUS_PASSWORD }}
+  CI_PROJECT_ID: 49355
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   FileChanges:
     runs-on: ubuntu-latest
@@ -46,41 +49,41 @@ jobs:
           echo "Final file status except check: $exc"
           echo "run=$exc" >> $GITHUB_OUTPUT
   linux_phase:
-    needs: [BranchJobLinux, MasterDeployJobLinux]
+    needs: [ BranchJobLinux, MasterDeployJobLinux ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage linux"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage linux"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage linux"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage linux"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
   page_phase:
-    needs: [linux_phase, pages]
+    needs: [ linux_phase, pages ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage page"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage page"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage page"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage page"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
   trigger_apps_phase:
-    needs: [page_phase, trigger-3d-gan, trigger-coopautopilot, trigger-kipf-gnn, trigger-doppelkopf, trigger-sentiment, trigger-tictactoe, trigger-mnist-vae, trigger-mnistcalc]
+    needs: [ page_phase, trigger-3d-gan, trigger-coopautopilot, trigger-kipf-gnn, trigger-doppelkopf, trigger-sentiment, trigger-tictactoe, trigger-mnist-vae, trigger-mnistcalc ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage trigger_apps"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage trigger_apps"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage trigger_apps"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage trigger_apps"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   BranchJobLinux:
     needs: FileChanges
@@ -616,7 +619,7 @@ jobs:
           REPO: ${{github.repository}}
 
   pages:
-    needs: [linux_phase, FileChanges]
+    needs: [ linux_phase, FileChanges ]
     if: ${{ !cancelled() && needs.linux_phase.result == 'success' &&  github.ref_name == 'master' && needs.FileChanges.outputs.runpages == 'true' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
diff --git a/.github/workflows/misc.yml b/.github/workflows/misc.yml
--- a/.github/workflows/misc.yml
+++ b/.github/workflows/misc.yml
@@ -6,22 +6,25 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 33335
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
+  CI_PROJECT_ID: 33335
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   test_phase:
-    needs: []
+    needs: [ ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage test"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage test"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage test"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage test"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   masterJobLinux:
     needs: test_phase
diff --git a/.github/workflows/mnist-vae.yml b/.github/workflows/mnist-vae.yml
--- a/.github/workflows/mnist-vae.yml
+++ b/.github/workflows/mnist-vae.yml
@@ -6,35 +6,38 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 59549
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
-  cibuild : ${{ secrets.SE_NEXUS_PASSWORD }}
+  CI_PROJECT_ID: 59549
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+  cibuild: ${{ secrets.SE_NEXUS_PASSWORD }}
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   build_phase:
-    needs: [BuildVQVAE, BuildBetaVAE, BuildCVAE, BuildVAE]
+    needs: [ BuildVQVAE, BuildBetaVAE, BuildCVAE, BuildVAE ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage build"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage build"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage build"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage build"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
   test_phase:
-    needs: [build_phase, TestPretrainedVAE, TestPretrainedBetaVAE, TestPythonPretrainedVQVAE, TestCPPPretrainedVQVAE, TestPretrainedCVAE]
+    needs: [ build_phase, TestPretrainedVAE, TestPretrainedBetaVAE, TestPythonPretrainedVQVAE, TestCPPPretrainedVQVAE, TestPretrainedCVAE ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage test"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage test"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage test"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage test"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   BuildVAE:
     runs-on: ubuntu-latest
@@ -275,7 +278,7 @@ jobs:
         run: docker exec build-container bash -c "$SCRIPT"
 
   InstallVAE:
-    needs: [TestPretrainedVAE, test_phase]
+    needs: [ TestPretrainedVAE, test_phase ]
     if: ${{ !cancelled() && needs.test_phase.result == 'success'      && github.ref_name != 'master' && needs.TestPretrainedVAE.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
@@ -300,7 +303,7 @@ jobs:
         run: docker exec build-container bash -c "$SCRIPT"
 
   InstallBetaVAE:
-    needs: [TestPretrainedBetaVAE, test_phase]
+    needs: [ TestPretrainedBetaVAE, test_phase ]
     if: ${{ !cancelled() && needs.test_phase.result == 'success'      && github.ref_name != 'master' && needs.TestPretrainedBetaVAE.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
@@ -325,7 +328,7 @@ jobs:
         run: docker exec build-container bash -c "$SCRIPT"
 
   InstallCVAE:
-    needs: [TestPretrainedCVAE, test_phase]
+    needs: [ TestPretrainedCVAE, test_phase ]
     if: ${{ !cancelled() && needs.test_phase.result == 'success'      && github.ref_name != 'master' && needs.TestPretrainedCVAE.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
@@ -350,7 +353,7 @@ jobs:
         run: docker exec build-container bash -c "$SCRIPT"
 
   InstallVQVAE:
-    needs: [TestPythonPretrainedVQVAE , TestCPPPretrainedVQVAE, test_phase]
+    needs: [ TestPythonPretrainedVQVAE , TestCPPPretrainedVQVAE, test_phase ]
     if: ${{ !cancelled() && needs.test_phase.result == 'success'      && github.ref_name != 'master' && needs.TestPythonPretrainedVQVAE.result == 'success' && needs.TestCPPPretrainedVQVAE.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
@@ -375,7 +378,7 @@ jobs:
         run: docker exec build-container bash -c "$SCRIPT"
 
   DeployPretrainedVAE:
-    needs: [TestPretrainedVAE, test_phase]
+    needs: [ TestPretrainedVAE, test_phase ]
     if: ${{ !cancelled() && needs.test_phase.result == 'success' &&  github.ref_name == 'master' && needs.TestPretrainedVAE.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
@@ -400,7 +403,7 @@ jobs:
         run: docker exec build-container bash -c "$SCRIPT"
 
   DeployPretrainedBetaVAE:
-    needs: [TestPretrainedBetaVAE, test_phase]
+    needs: [ TestPretrainedBetaVAE, test_phase ]
     if: ${{ !cancelled() && needs.test_phase.result == 'success' &&  github.ref_name == 'master' && needs.TestPretrainedBetaVAE.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
@@ -425,7 +428,7 @@ jobs:
         run: docker exec build-container bash -c "$SCRIPT"
 
   DeployPretrainedCVAE:
-    needs: [TestPretrainedCVAE, test_phase]
+    needs: [ TestPretrainedCVAE, test_phase ]
     if: ${{ !cancelled() && needs.test_phase.result == 'success' &&  github.ref_name == 'master' && needs.TestPretrainedCVAE.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
@@ -450,7 +453,7 @@ jobs:
         run: docker exec build-container bash -c "$SCRIPT"
 
   DeployPretrainedVQVAE:
-    needs: [TestPythonPretrainedVQVAE , TestCPPPretrainedVQVAE, test_phase]
+    needs: [ TestPythonPretrainedVQVAE , TestCPPPretrainedVQVAE, test_phase ]
     if: ${{ !cancelled() && needs.test_phase.result == 'success' &&  github.ref_name == 'master' && needs.TestPythonPretrainedVQVAE.result == 'success' && needs.TestCPPPretrainedVQVAE.result == 'success' }}
     runs-on: ubuntu-latest
     timeout-minutes: 120
diff --git a/.github/workflows/turtlebot.yml b/.github/workflows/turtlebot.yml
--- a/.github/workflows/turtlebot.yml
+++ b/.github/workflows/turtlebot.yml
@@ -6,34 +6,37 @@ on:
   workflow_dispatch:
   pull_request:
 env:
-  CI_PROJECT_ID : 72226
-  CI_API_V4_URL : https://git.rwth-aachen.de/api/v4
-  GITLABTOKEN : ${{ secrets.GITLABTOKEN }}
+  CI_PROJECT_ID: 72226
+  CI_API_V4_URL: https://git.rwth-aachen.de/api/v4
+  GITLABTOKEN: ${{ secrets.GITLABTOKEN }}
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   build_phase:
-    needs: [TestBuild]
+    needs: [ TestBuild ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage build"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage build"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage build"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage build"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
   train_phase:
-    needs: [build_phase, TestTrain]
+    needs: [ build_phase, TestTrain ]
     if: ${{ !cancelled()}}
     runs-on: ubuntu-latest
     steps:
-        - run: |
-            echo "Finished stage train"
-          if: ${{!contains(needs.*.result, 'failure')}}
-        - run: |
-            echo "Failed stage train"
-            exit 1
-          if: ${{contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Finished stage train"
+        if: ${{!contains(needs.*.result, 'failure')}}
+      - run: |
+          echo "Failed stage train"
+          exit 1
+        if: ${{contains(needs.*.result, 'failure')}}
 
   TestBuild:
     runs-on: ubuntu-latest
